baseURL = "https://quikzens.netlify.app/"
languageCode = "id-id"
title = "Febrian Amir | @quikzens"
disableKinds = ["taxonomy", "term"]
[permalinks]
  tulisan = "/:filename/"
  rekomendasi = "/:filename/"
  kodezens = "/:filename/"