baseURL = "https://quikzens.netlify.app/"
languageCode = "id-id"
title = "Quikzens"
disableKinds = ["taxonomy", "term"]
[permalinks]
  tulisan = "/:filename/"
  rekomendasi = "/:filename/"
  buku = "/:filename/"